file_converter:file_converter.o
	gcc file_converter.o -o file_converter
file_converter.o:file_converter.c
	gcc -Wall -c file_converter.c
clean_fc:
	rm file_converter file_converter.o
symbol_func:symbol_func.o
	gcc symbol_func.o -o symbol_func
symbol_func.o:symbol_func.c
	gcc -Wall -c symbol_func.c
clean_sf:
	rm symbol_func symbol_func.o
