ServerClient:
	gcc TCPEchoServer.c DieWithError.c HandleTCPClientStruct.c function.c -o struct_server
	gcc TCPEchoClientStruct.c DieWithError.c -o struct_client
clean:
	rm struct_client struct_server
